### ISSUE TITLE
In ClientContext.write(), tcp_sndbuf() return 0

### ISSUE THREAD

**Issue by MS1987** [Duet3D/CoreESP8266#1]
Hi, dc42.
I use  this coreEsp8266 lib to setup a esp8266 webserver. Sometimes it runs ok, but  sometimes it always block.
I trace it and find  in the function "ClientContext.write()", tcp_sndbuf() return 0 during a long time. It seems that the lwip cannot receive ack of the last package which lead to no room for the next package.
This situation happens very frenquencly and randomly.
I think you have met this question because I find you have add "abort()" function in this write function. Do you know how to avoid it ?

**Comment by dc42** [comment]
The call to abort was added by chrishamm. We are not very happy with the ESP8266 webserver, and I am currently rewriting the wifi code. The new code will run the web server on the Duet main processor instead, and only use the ESP8266 to run the wifi and the TCP/IP stack.

**Comment by MS1987** [comment]
Can you share what is wrong with ESP8266 webserver? The heap not large enough ? Or there is bug in the lib?

**Comment by dc42** [comment]
It's not written to high-integrity standards (which sadly is the case with most Arduino code) and it crashes repeatedly in certain network environments. The original version is slow. We had to implement some significant changes to get it to run at a reasonable speed.

**Comment by MS1987** [comment]
I agree with your opinion! Sometime it runs very well, however, sometimes it crashes all the time. Maybe it cannot adapt to the complex network environment.
I am looking forward to your modification.
